1.定义一个函数，运行该函数后会连续打印三次："重要的事情说三遍！"

In [68]:
def imp_repeat():
    print(3*"重要的事情说三遍! ") 
imp_repeat()  

重要的事情说三遍! 重要的事情说三遍! 重要的事情说三遍! 


2.定义一个判断字符串的长度是否大于10的函数,并判断s='faldkjglkaj'长度是否大于10.

In [6]:
def is_bigger(s):
    return len(s)>10
s='faldkjglkaj'
is_bigger(s)

True

3.利用函数标记一个列表，奇数标记为1，偶数标记为2，并且统计一下奇数和偶数的数量。
例如：[1,4,2,4,2,9,5]，得到[1,2,2,2,2,1,1]

In [19]:
def a_list(L):
    nlst = []
    for i in L:
        if i%2 == 0:
            nlst.append(2)
        else:
            nlst.append(1)
    a = nlst.count(1)
    b = nlst.count(2)
    print(nlst)
    print('the number of odd is %d' %a)
    print('the number of even is %d' %b)

In [20]:
L = [1,4,2,4,2,9,5]
a_list(L)

[1, 2, 2, 2, 2, 1, 1]
the number of odd is 3
the number of even is 4


4.创建一个1到10的数组，然后逆序输出。

In [21]:
import numpy as np

In [36]:
a = np.arange(1,11)
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

5.从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。

In [40]:
b = np.random.randint(1,11,10)
c = [i for i in b if i%2 != 0]
print(b)
print(c)

[10  3  6  1 10  4  1  5  8  5]
[3, 1, 1, 5, 5]


6.从1到10中随机选取10个数，构成一个长度为10的数组，并将其排序。获取其最大值、最小值、求和、开根号、余弦值，如果结果为多小数的，保留2位小数。

In [42]:
b = np.random.randint(1,11,10)
b

array([1, 5, 3, 6, 7, 7, 5, 1, 4, 5])

In [43]:
np.sort(b)

array([1, 1, 3, 4, 5, 5, 5, 6, 7, 7])

In [47]:
print(np.max(b))
print(np.min(b))
print(np.sum(b))
print(np.round(np.sqrt(b),2))
print(np.round(np.cos(b),2))

7
1
44
[1.   2.24 1.73 2.45 2.65 2.65 2.24 1.   2.   2.24]
[ 0.54  0.28 -0.99  0.96  0.75  0.75  0.28  0.54 -0.65  0.28]


7.从1到10中随机选取10个数，大于3和小于8的取负数,所得结果存放在1个列表中

In [49]:
b = np.random.randint(1,11,10)
result = []
for i in b:
    if i>3 and i <8:
        result.append(-i)
    else:
        result.append(i)
print(result)

[3, 3, -5, 9, -4, 3, 1, 9, 9, 8]


### `可以用where完成这个吗？`

8.创建一个长度为10并且除了第五个值为1其余的值为2的向量。

In [56]:
a = np.ones(10,dtype='int')
b = a+1
b[4] = 1
b

array([2, 2, 2, 2, 1, 2, 2, 2, 2, 2])

9.获取数组 a 和 b 中的共同项（索引位置相同，值也相同）。 a = np.array([1,2,3,2,3,4,3,4,5,6])，b = np.array([7,2,10,2,7,4,9,4,9,8])

In [61]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[np.where(a==b)]

array([2, 2, 4, 4])